### PR TITLE
Combine spatial data and xarray point obs

### PR DESCRIPTION
**Pull request by zmoon**
xref: https://github.com/NOAA-CSL/MELODIES-MONET/issues/115

* new `combine_da_to_da` utility function
  - currently used in MM aircraft branch [here](https://github.com/NOAA-CSL/MELODIES-MONET/blob/b8d150871aaf9a5bc08e98d7aba7ecbb623385e5/melodies_monet/driver.py#L688)
* ~~`.monet` `combine_da` methods~~
  - maybe later create a new combine method that could take xarray _or_ df point data input
* improve docstrings of some combine functions and `.monet` accessor methods

### CODE REVIEW

**Comment by zmoon** [comment]
@bbakernoaa when you get a chance could you let me know what remains to be done here?

**Comment by bbakernoaa** [comment]
I don't think anything else needs to be done here.  We have been using this in the MELODIES-MONET project so I think it should be ready to merge.

**Comment by zmoon** [comment]
@bbakernoaa in the new functions the docstring parameters listed don't match the signature in some cases, and for some I am not sure how to fix. Would you be able to have a quick go at that?

**Comment by bbakernoaa** [comment]
I'll try to take a look at it soon

**Comment by zmoon** [comment]
@bbakernoaa I made some edits. I am a little confused though: for `combine_da` it seems like the `data` argument should be a DataFrame, as it is being passed to `combine_da_to_df` in the `df` position, but the checks in `combine_da` make sure that it is an xarray Dataset. The `combine_da` signature seems to suggest the intention was for the new `combine_da_to_da` to be used instead?

**Comment by bbakernoaa** [comment]
@zmoon lets talk about this tomorrow as I'm a little confused

**Comment by zmoon** [comment]
@rschwant could you point to me how/where in MM you are using this?

**Pull request merged**
